### ISSUE TITLE
What's causing this issue?

### ISSUE THREAD

**Issue by LWFlouisa** [michaeldv/gabbler#1]
Traceback (most recent call last):
	1: from gabbler.rb:7:in `<main>'
/var/lib/gems/2.5.0/gems/gabbler-0.1.0/lib/gabbler/generator.rb:38:in `sentence': undefined method `[]' for nil:NilClass (NoMethodError)

No matter how I arrange the gabbler script, I always get this error. Even when that particular line is not present.

If my program has 28 lines, I shouldn't be getting an error on line 38.

**Comment by LWFlouisa** [comment]
Nevermind, apparently it's not designed for random decisions.
